== Preliminary Resources for Further Peppler Research

=== Bender Family History in New York and Nebraka

==== FindAGrave References

These uncited stories tell the the Bender family history, first in New York, then Indiana and finally in and Nebraka.

This find-a-grave biography accompanies the memorial for https://www.findagrave.com/memorial/63678411/frederick-bender[Frederick Bender (21 Aug 1837 to 28 May 1918)] that exaplsins *Johann Frierich Bender and one of his sons died in Indiana*. 

____
Frederick was the first child born to Johann and Alora Bender in Albany, New York. At the age of 5, Frederick
and his parents moved to Fort Wayne, Indiana. He married Anna Marie Fuchshuber and five children were born in
Indiana to this union. After two older sons, Martin and Louis, came to Seward County looking for employment, the
entire family moved west and settled on land purchased from the Burlington Railroad in 1887. The family at that time
consisted of Frederick, Anna, his mother, Alora, and children Elizabeth, Christina, John Frederick, and William.
*His father and one son had died in Indiana.* (Taken from Seward County Nebraska 1982)
____

The source of this information may be FamilySearch. See the next section below.

==== FamilySearch  Biography

The find-a-grave information about may have been take from the https://www.familysearch.org/tree/person/collaborate/LHLT-92L[colloration tab] for the Johann Friedrich Bender entry in the FamilySearch tree.
The same note accopanies the entry for  https://www.familysearch.org/tree/person/collaborate/LBHW-89D[Eleonore Christine Rühl], his wife.

Comment: I emailed the author through FamilySearch and he replied to say he beilieved he got it from one of his aunts and would check further on the source.

____
Frederick Bender was the son of John Frederick Bender who immigrated from Darmstadt, Hesse, Germany to America in 1836, settling near Albany, New York.
A son Frederick was born to them August 21, 1837. His father worked for a time as a teamster to pull the boats through the Erie Canal. Not liking the
country, he emigrated westward by covered wagon with his brother John Bender and their families. They traveled on the Wayne Trace Road coming to the
Soest Community near Fort Wayne, Indiana. They settled here, clearing the trees from the land, built a log cabin until a more substantial house could
be built. Three more children were born to the family. The fathers were charter members of the Emmanuel Lutheran Church which was organized Dec 25, 1845,
at Soest on the [Wayne] Trace Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the
farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this
union were born five sons and two daughters. The youngest son George
died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both
are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska
while working on the railroad. They wrote to their father of land
available for settlers. Frederick Bender purchased 160 acres of land
from the Burlington Railroad for $9.00 an acre in Section 21 southwest
of the village of Ruby. Later he sold this to his sons. In July 1887 he
purchased 80 acres more for himself in Section 28, southwest of Ruby. In
October of that year he moved his family to Nebraska. Coming with him
were his wife, his aged mother; daughters Elizabeth and Cristina, sons
John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel
Lutheran Chruch which was organized Feb 25, 1889, the services being
held in the District No 7 school house. He was to purchase three more
acres of land in the northwest corner of section 27, one half mile east
of his home, which he donated to the Immanuel Congregation for church
property. Here a church was built, a parsonage and a plot set aside for
a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891,
the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May
28, 1918. His son John Frederick would inherit the land. Another 66
acres of land had been purchased across the road from him in Section 21,
for his son William and his family. John Frederick, known as Fred,
married Martha Eckhardt April 18, 1895. To this union were born five
sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife
1959) Of the family, Gerhard Bender is the present owner of the farm.
Three of his sisters are still living, one sister and four brothers have
passed away.
____

The FamilySearch Life Sketch for
https://www.familysearch.org/tree/person/details/9ZS9-YFF[Frederick Bender] explains

____
On 20 July 1862, Frederick Bender and Anna Marie Fuchshuber were married
by Rev. Charles Adams at St. Mark’s Lutheran Church, on Thiele Road in
Allen County, Pleasant Township, Indiana, in a log cabin church. Their
youngest son, George, died of diptheria at age 8, as did his grandfather
John Frederick, on November 19, 1871. Both are buried at the Emmanuel
Lutheran Church cemetery, Soest, Indiana. In the 1880s, the two older
Bender sons came west to Seward County, Nebraska, while working for the
railroad. Fred purchased 80 acres southwest of Ruby, and in October 1887
he moved his family to Nebraska. Coming with him was his mother, Alora.
He became a charter member of the Immanuel Lutheran Church, which was
organized 25 February 1889, with services held in the district school
house. He purchased three more acres of land, one half mile east of his
home, which he donated to the Immanuel Congregation. Here they built a
church, a parsonage, and a cemetery plot. Eleonora Bender, his mother,
passed away on 12 December 1891, and she was the first person buried in
the cemetery.
____

==== Bender Zugehörigkeit zu Sankt Johannis Gemeinde

They were members (who were--the Benders, too??) of the Sankt Johannis Gemeinde, just north of Emmanuel
(Soest), on the esat side of Wayne Trace just north day of I-469. They
were a splinter congregation of Emmanuel according it
http://www.emmanuelsoest.org/our-history/[history].

=== Bender Leads

Johann "John" Bender’s Find-a-grave
https://www.findagrave.com/memorial/68838340/johannes-bender[memorial]
contains an image of a newspaper snippet about his funeral that says ``a
pioneer Adams township farmer''. Citation:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/68838340/johannes-bender : accessed
13 July 2022), memorial page for Johannes Bender (8 Sep 1808–20 Apr
1886), Find a Grave Memorial ID 68838340, citing Soest Emmanuel Lutheran
Cemetery, Fort Wayne, Allen County, Indiana, USA ; Maintained by JC
(contributor 46984629) .
____

His wife’s memorial also has newpaper clippings. Citation:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/141541158/katharina-bender :
accessed 13 July 2022), memorial page for Katharina Bender (8 Jun
1809–13 Mar 1897), Find a Grave Memorial ID 141541158, citing Soest
Emmanuel Lutheran Cemetery, Fort Wayne, Allen County, Indiana, USA ;
Maintained by MJ (contributor 47177744) .
____

* The source of the story may be a local volume on fmily gustirt.
* Soest Emmanuel Church Records
* Adams or Marion Twp Histories
* Land Records

===== FindAGrave Parentage Information for Joh. Jacob Pppler

The Find-A-Grave page for
https://www.findagrave.com/memorial/78479111/pep[Johann Jacob Pppler]
give his parentage:

____
Son of Johann Ludwig Peppler and Katharina Margarethe Meissner Peppler.
Husband of Maria Magdalene Platt Peppler
____

____
Gravesite Details
____

____
Johan was born in Rodheim near Grodrigun, Germany.
____

but the source of thisinformation is not mentioned.

Citation for Johann Jacob Peppler:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/78479111/johan-jacob-peppler :
accessed 06 July 2022), memorial page for Johan Jacob Peppler (21 Nov
1810–25 Apr 1873), Find a Grave Memorial ID 78479111, citing Saint John
Evangelical Lutheran Church Cemetery, Marion Township, Allen County,
Indiana, USA ; Maintained by Annis Jean Hite Patee (contributor
46907132).
____

There is a Heimatverein in Rodheim-Bieber in which the late Heinz
Peppler was the joint-leader of the Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Village
and family history] working group.

===== FamilySearch Wiki Hesse

https://www.familysearch.org/en/wiki/Hesse_(Hessen),_German_Empire_Genealogy

===== History of the Reformed Churches in Germany

* Britanncia article on
https://www.britannica.com/topic/Presbyterian-churches[Reformed and
Presbyterian churches] discusses Reformed Churches in Germany.
* FamilySearch wiki
https://www.familysearch.org/en/wiki/German_Reformed_Church_in_the_United_States[German
Reformed Churches in the United States]
* FamilySearch wiki
https://www.familysearch.org/en/wiki/Determining_the_Church_Your_Ancestor_Attended[Determing
the Church Your Ancestor Attended]
* United Church of Christ page on
https://www.ucc.org/about-us_short-course_the-german-reformed-church/[The
German Reformed Church]
* https://erhistoricalsociety.org/[Evaneglical and Reformed Historical
Society]
