==== Uncited Stores about Bender Family in New York and Nebraka

According to a short short accomapnying the FindAGrave https://www.findagrave.com/memorial/63678411/frederick-bender[memorial for Frederick Bender (21 Aug 1837 to 28 May 1918)]:

____

Frederick was the first child born to Johann and Alora Bender in Albany, New York. At the age of 5, Frederick and his parents moved to Fort Wayne, Indiana. He married Anna Marie Fuchshuber and five children were born in Indiana to this union. After two older sons, Martin and Louis, came to Seward County looking for employment, the entire family moved west and settled on land purchased from the Burlington Railroad in 1887. The family at that time consisted of Frederick, Anna, his mother, Alora, and children Elizabeth, Christina, John Frederick, and William. His father and one son had died in Indiana. (Taken from Seward County Nebraska 1982)
____


This Bender family story of their time in New York state is from the FamilySearch page for Johann Friedrich Bender, the https://www.familysearch.org/tree/person/collaborate/LHLT-92L[Collaborate tab]. See **Note** 
from the _Frederik Bender from Bender File, 1978_. I was told by the person who posted it that he beilieved he got it from one of his aunts:

____
Frederick Bender was the son of John Frederick Bender who immigrated from Darmstadt, Hesse, Germany to America in 1836, settling near Albany, New York. A son Frederick was born to them August 21, 1837. His father worked for a time as a teamster to pull the boats through the Erie Canal. Not liking the country, he emigrated westward by covered wagon with his brother John Bender and their families. They traveled on the Wayne Trace Road coming to the Soest Community near Fort Wayne, Indiana. They settled here, clearing the trees from the land, built a log cabin until a more substantial house could be built. Three more children were born to the family. The fathers were charter members of the Emmanuel Lutheran Church which was organized Dec 25, 1845 at Soest on the Trace Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this union were born five sons and two daughters. The youngest son George died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska while working on the railroad. They wrote to their father of land available for settlers. Frederick Bender purchased 160 acres of land from the Burlington Railroad for $9.00 an acre in Section 21 southwest of the village of Ruby. Later he sold this to his sons. In July 1887 he purchased 80 acres more for himself in Section 28, southwest of Ruby. In October of that year he moved his family to Nebraska. Coming with him were his wife, his aged mother; daughters Elizabeth and Cristina, sons John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel Lutheran Chruch which was organized Feb 25, 1889, the services being held in the District No 7 school house. He was to purchase three more acres of land in the northwest corner of section 27, one half mile east of his home, which he donated to the Immanuel Congregation for church property. Here a church was built, a parsonage and a plot set aside for a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891, the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May 28, 1918. His son John Frederick would inherit the land. Another 66 acres of land had been purchased across the road from him in Section 21, for his son William and his family. John Frederick, known as Fred, married Martha Eckhardt April 18, 1895. To this union were born five sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife 1959) Of the family, Gerhard Bender is the present owner of the farm. Three of his sisters are still living, one sister and four brothers have passed away.
____


The story of how Friedrich Bender came to Allen county is described in a https://www.familysearch.org/tree/person/collaborate/LBHW-89D[Note]
attached to Eleonore Christine Rühl, Friedrich’s wife. The Note explains:

____
Frederick Bender was the son of John Frederick Bender who immigrated
from Darmstadt, Hesse, Germany to America in 1836, settling near Albany,
New York. A son Frederick was born to them August 21, 1837. His father
worked for a time as a teamster to pull the boats through the Erie
Canal. Not liking the country, he emigrated westward by covered wagon
with his brother John Bender and their families. They traveled on the
Wayne Trace Road coming to the Soest Community near Fort Wayne, Indiana.
They settled here, clearing the trees from the land, built a log cabin
until a more substantial house could be built.> Three more children were
born to the family. The fathers were charter members of the Emmanuel
Lutheran Church which was organized Dec 25, 1845 at Soest on the Trace
Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the
farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this
union were born five sons and two daughters. The youngest son George
died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both
are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska
while working on the railroad. They wrote to their father of land
available for settlers. Frederick Bender purchased 160 acres of land
from the Burlington Railroad for $9.00 an acre in Section 21 southwest
of the village of Ruby. Later he sold this to his sons. In July 1887 he
purchased 80 acres more for himself in Section 28, southwest of Ruby. In
October of that year he moved his family to Nebraska. Coming with him
were his wife, his aged mother; daughters Elizabeth and Cristina, sons
John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel
Lutheran Chruch which was organized Feb 25, 1889, the services being
held in the District No 7 school house. He was to purchase three more
acres of land in the northwest corner of section 27, one half mile east
of his home, which he donated to the Immanuel Congregation for church
property. Here a church was built, a parsonage and a plot set aside for
a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891,
the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May
28, 1918. His son John Frederick would inherit the land. Another 66
acres of land had been purchased across the road from him in Section 21,
for his son William and his family. John Frederick, known as Fred,
married Martha Eckhardt April 18, 1895. To this union were born five
sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife
1959) Of the family, Gerhard Bender is the present owner of the farm.
Three of his sisters are still living, one sister and four brothers have
passed away.
____

The FamilySearch Life Sketch for
https://www.familysearch.org/tree/person/details/9ZS9-YFF[Frederick Bender] explains

____
On 20 July 1862, Frederick Bender and Anna Marie Fuchshuber were married
by Rev. Charles Adams at St. Mark’s Lutheran Church, on Thiele Road in
Allen County, Pleasant Township, Indiana, in a log cabin church. Their
youngest son, George, died of diptheria at age 8, as did his grandfather
John Frederick, on November 19, 1871. Both are buried at the Emmanuel
Lutheran Church cemetery, Soest, Indiana. In the 1880s, the two older
Bender sons came west to Seward County, Nebraska, while working for the
railroad. Fred purchased 80 acres southwest of Ruby, and in October 1887
he moved his family to Nebraska. Coming with him was his mother, Alora.
He became a charter member of the Immanuel Lutheran Church, which was
organized 25 February 1889, with services held in the district school
house. He purchased three more acres of land, one half mile east of his
home, which he donated to the Immanuel Congregation. Here they built a
church, a parsonage, and a cemetery plot. Eleonora Bender, his mother,
passed away on 12 December 1891, and she was the first person buried in
the cemetery.
____

The FindAGrave memorial for
https://www.findagrave.com/memorial/63678411/frederick-bender[Frederick Bender Jr] also gives this sketch of his life:

____
Frederick was the first child born to Johann and Alora Bender in Albany,
New York. At the age of 5, Frederick and his parents moved to Fort
Wayne, Indiana. He married Anna Marie Fuchshuber and five children were
born in Indiana to this union. After two older sons, Martin and Louis,
came to Seward County looking for employment, the entire family moved
west and settled on land purchased from the Burlington Railroad in 1887.
The family at that time consisted of Frederick, Anna, his mother, Alora,
and children Elizabeth, Christina, John Frederick, and William. His
father and one son had died in Indiana. (Taken from Seward County
Nebraska 1982)
____


