= Peppler and Bender Genealogy Research
:toc:
:stylesheet: dark.css
:stylesdir: ../skins 

== The Pepplers and Benders from Rodheim an der Bieber

=== Introduction

The first Peppler family to settle in Allen County, Indiana, emigrated in April 1857 from *Rodheim an der Bieber* (Rodheim on the Bieber,
a stream), a small village in the Grand Duchy of Hessen, today the federal state of Hesse, one of 17 German states. On April 1,
1954 (citaiton: from Hesseniinfosystemg gazetteer or other subsource from this website, or even wikipedia) *Rodheim an der Bieber* was renamed *Rodheim-Bieber*. 

Four Pepplers from Rodheim emigrated in 1847. A search for "Peppler" in the Hessian emigrant https://www.lagis-hessen.de/en/subjects/index/sn/ha[database] gives these https://www.lagis-hessen.de/en/subjects/gsearch/sn/ha?q=Peppler&submit=LAGIS+Search[results].
todo: place map here
todo: Get into German history next.

=== Early Clues
Because Germany did not become a nation-state until 1871, no national records of any genealogical significance exist for ancestors who emigrated
in the mid nineteenth century. The most important German genealogical records are local parish church books, which began to be kept after the 
Reformation. In ??? Martin Luter published his 95?7,  these in ???. After the Peace of Augsburg in..Peace of Augusburg... They list parentage, birth date, confirmation dates, marriages, and so on. 

But to find the home town or village, we have to start with clues we find in U.S. records and work backwards, connecting the dots as we go.

After German ancestors arrive in the U.S., we usually can find them in U.S. censuses, which began "in 1790, and has been taken every ten years since. 
(https://www.archives.gov/research/census[National Archives, Census Records])."
find them in passenger ship arrival lists. Passenger lists of ships arriving from foreign ports were a legal requirement that  bean as early as ????. 

To figuing out their German hometown 

****
For centuries ``Germany'' existed as an empire composed of a conglomeration of principalities (Fürstentum), duchies
(Herzogtum), grand duchies (Großherzogtum), free cities, etc., each with its own ruler or prince. In ??? there were over of over 300 such ???, At the top of the
ruling hierarchy stood the Emperor, crowned by the Pope (although for practical reasons he was crowned by proxy by the Archbishop ???, in
Aachen??). large like ????). The Protestant Reformation ensured a the empire late of cohesion, but it gave rise to church books….. todo:
mention Heiliges Römanisches Reich was used – quote Pete Wilson – in the 17th century)

Perhaps comment on size of the states within the empire, mentiong that were some small regions like the the principalites of
Schaumburg/Schumburg-Lippe???

It wasn’t until the 17?? century [Peter Wilson quote from youtube interview] that the
Empire was also referred to as the the Holy Roman Empire (Der Heiliges
Römisches Reich).

The Empire came to an end in 1806 when Napolean, with the support of 17?
German princes, forced the last empeor Francis II to abdicate or face
war. With the abdication came the dissolution of the Holy Roman Empire.

In 1806 Napolean with the help of 16 German princes forced the last German emperor to abdicate or face war.

The Pepplers came from the Grand Duchy of Hesse which was created in
1806 (the year the last Holy roman Emperor abdicated and dissolved the
Holy Roman Empire of the German Nation), just three years before the
birth of our 3x great grandfather, Johan Jokab Beppler’s birth. 
****

The Beppler surname later became Peppler. Johann Jakob nmarried Magdelane
Platt in ????. They would have three children. Only the first born would
have a long life.

* Johann Jacob Peppler (1810-1873), his wife
* Magdelane nee Platt Peppler (1810-1901), and their three children:
** Ludwig ``Louis'' Peppler" (1843-1914)
** Johann Jakob Peppler (1845-1873)
** Georg Andreas Peppler (1851-1857)

=== Tracing the Clues

We know they are our 3x greatgrandparents from several clues. On date???
19??? the News-Sentinel??? newspaper article described the 50th wedding
anniversity celebration for Louis Peppler and his wife ????.

todo: include a screen print of the article here.

todo: include the articles text, but first key excerpts from the text
(and caption) that mention Walter and Mae Behrman

???, acccompanied by large photo showing the couple surrounded by many
friends and family.

todo: include the article and, after mentioning Walter and Mae Pepperl,
give the articles text.

where they lived:

* census records
* marriage records of their children
* plat descriptions
* land record: deed book index and deed.
* Relationship to the Benders of Fellinghuasen.

other clues:

* Soest history with Sankt Johannis
* Hessiche Familenkunde Sep 1989 article
* Marriage of Mary Bender of Ludwig "Louis" Peppler
** A peppler help build the presnet Soest Emmanuel church
** Walter Peppler
* Sankt Johannis Records

At that time, Germany was not yet united as a nation, rather it existed
as an association of states that included the sate of Hesse. Rodheinm
today is called Rodheim-Bieber, and it is located over 150 miles south
of the home towns of the Krueckebergs and the Behrmans, whose villages
in northern Germany were relatively close.

==== Marriage of Ludwig "Louis" Peppler to daughter of the Benders from Fellinghausen

Ludwig "Louis" married Mary Bender, who was born in Indiana, but whose
parents were from Fellinghausen, Hessen-Darmstadt, very close to
Rodheim-Bieber. Who else was from Fellinghausen–the Felds? Did they all
come in chain-migration?

todo: create a timeline and map of where they lived in old country and
where they lived in Marion twp, allen, Indiana.

==== FindAGrave Parentage Information for Joh. Jacob Pppler

The Find-A-Grave page for
https://www.findagrave.com/memorial/78479111/pep[Johann Jacob Pppler]
give his parentage:

____
Son of Johann Ludwig Peppler and Katharina Margarethe Meissner Peppler.
Husband of Maria Magdalene Platt Peppler
____

____
Gravesite Details
____

____
Johan was born in Rodheim near Grodrigun, Germany.
____

but the source of thid information is not mentioned.

Citation for Johann Jacob Peppler:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/78479111/johan-jacob-peppler :
accessed 06 July 2022), memorial page for Johan Jacob Peppler (21 Nov
1810–25 Apr 1873), Find a Grave Memorial ID 78479111, citing Saint John
Evangelical Lutheran Church Cemetery, Marion Township, Allen County,
Indiana, USA ; Maintained by Annis Jean Hite Patee (contributor
46907132).
____

=== Evidence that Rodheim is the Pepplers Place of Origin

Some of the evidence is from tombstone photos from the Sankt Johanis Gemeinde cemetery in Marion twp, Allen County, Indiana, whose history is now briefly sketched.

==== Sketch of Infomation on Sankt Johannis Gemeinde, Maion twp, Allen County, Indiana

include::sankt-johannis.a[]

==== Tombstone Inscriptions Name Rodheim as Place of Origin

The tombstones of Maria Magdalene Platt and Johann Jokab Peppler give,
respectively, *Rodheim, unclear [Gießen?], Großherzogtum (Grandduchy)
Hessen* and *Rodheim in the Grandducy of Hessen Darmstadt* as their
place of origin.

This is my transcription of the inscription on the tombstone image for
link:./images/Marie_Magdalene_Platt_tombstone.jpg[Marie Magdalene Platt Peppler]:

The inscription is in German and reads:

// Make this a table 
____
hier ruhet in Gott +
Marie Magdalene Peppler +
gebornne Platt +
Ehefrau von Joh. Jocab Peppler +
geb den 3. Jan 1810 +
in Rodheim bei [Giessen?] +
Großherzogtum Hessen-Darmstadt, Deutschland +
gest(orben) den 28. Jan. 1901 +
Alter 91 Jahre 25 Tage +
____

The translation is: +

____
here rests in God +
Marie Magdalene Peppler +
born Platt +
wife of Joh. Jocab Peppler +
born the 3rd Jan. 1810 +
in Rodheim in [unclear] +
Grand Duchy of Hessen-Darmstadt, Germany +
died 28th Jan 1901 +
age 91 years 25 days +
____

My transcription of the visible portion of the tombstone inscription for
link:./images/johann-jokab_peppler_headstone2.jpg[Johann Jacob Peppler] is:

____
hier ruhet in Gott +
geboren zu Rodheim +
bei Gie Großherzogtum Hessen +
Darmstadt
____

The translation is:

____
here rests in God born at Rodheim [unclear] Granduchy Hessen Darmstadt
____

Find-A-Grave give the parentage of Johann Jacobe Peppler, but it does
not have a cited source.

=== Which Rodheim?

Meyers Gazetteer lists four Rodheims: three in Hessen (which are listed
below) and one in Bayern:

* https://www.meyersgaz.org/place/20610041[Rodheim a/d Horloff; Rodheim, Giessen, OHessen, Hessen]
* https://www.meyersgaz.org/place/20610042[Rodheim vor der Höhe; Rodheim, Friedberg, OHessen, Hessen]
* https://www.meyersgaz.org/place/20610043[Rodheim-Bieber; Rodheim, Biedenkopf, Wiesbaden, Hessen-Nassau, Preussen]

which one is the Peppler’s Rodheim?

