15 Feb 1908 an 80-acre Schwalm farm is for sael, along with house, barns, windmilll, etc.
Buyers are told to inquire at *C.C.Schwalm Meat Market*, 902 Barr St.

Perhaps the reson I can't find Schwalm in the 1860 census, after all he marries in 1861, is his name is misspelled or transcribed--just a thought.

*todo:* Read the city dirtores from the 860s. The yhave township histories and information. The yalso have descriptions of churches, wards, etc. It is infomrative!

*todo:* Find his obituary.

This https://www.ancestry.com/discoveryui-content/view/1440226985:2469?tid=68081704&pid=122401936409&queryId=20a9ee11d03722a86071d04f502a85fc&_phsrc=KtD1980&_phstart=successSource[City Dirctory]
in 1867 gives his employer--I think!

=== Wards

In the 1860 City Dreictory there are five wards described on page 11. In the 1870 Directoy there are
In the 1870 census Philip Schwalm lives with his wife Christine Bender in the 8th ward. According to the 1870 City Dricectoyr, the 8th ward is:

iThe Schwalm children are show in this https://www.ancestry.com/family-tree/tree/169924734?cfpid=202200550226&dtid=100[tree]

Also the T. & W RR is the Toledo & Wabash RR.

